# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NextComb <- function(x, n) {
    .Call('combiter_NextComb', PACKAGE = 'combiter', x, n)
}

PrevComb <- function(x, n) {
    .Call('combiter_PrevComb', PACKAGE = 'combiter', x, n)
}

NextPerm <- function(x) {
    .Call('combiter_NextPerm', PACKAGE = 'combiter', x)
}

PrevPerm <- function(x) {
    .Call('combiter_PrevPerm', PACKAGE = 'combiter', x)
}

NextSubset <- function(x, n) {
    .Call('combiter_NextSubset', PACKAGE = 'combiter', x, n)
}

PrevSubset <- function(x, n) {
    .Call('combiter_PrevSubset', PACKAGE = 'combiter', x, n)
}

